In [1]:
import pandas as pd
df = pd.read_json('test.json')

In [2]:
df

,title,author,date,url,takeaways,text
0,Biden-Harris DOJ Prosecutor Targets Trans Whis...,"[Hans A. von Spakovsky, Sarah Parshall Perry]",2024-11-07,https://www.heritage.org/courts/commentary/bid...,[The weaponization of the U.S. Department of J...,The weaponization of the U.S. Department of Ju...
1,Wisconsin Public Schools’ Gender Policies Shut...,"[Thomas Jipping, Sarah Parshall Perry]",2024-10-23,https://www.heritage.org/gender/commentary/wis...,[Schools are generally in charge of matters su...,The Supreme Court has said that parents’ right...
2,United States v. Skrmetti: Oral Arguments Indi...,[Sarah Parshall Perry],2024-12-13,https://www.heritage.org/gender/commentary/uni...,[Tennessee is one of 26 states that have enact...,"On Wednesday, December 3, the U.S. Supreme Cou..."
3,Trump’s Transgender Orders Are Well Within Exe...,"[Paul J. Larkin, Sarah Parshall Perry]",2025-02-19,https://www.heritage.org/gender/commentary/tru...,[They claim the president’s directive prohibit...,"In two short weeks, President Donald Trump has..."
4,Follow the Law,[Sarah Parshall Perry],2025-02-27,https://www.heritage.org/gender/commentary/fol...,[Hurson’s decision halts the directives of Pre...,It’s difficult to envision a more dizzying exe...
...,...,...,...,...,...,...
299,Elizabeth Fender,[],NaT,https://www.heritage.org/staff/elizabeth-fender,[],Elizabeth Fender is the Senior Brand Advisor f...
300,Parents Beware!,[Rebecca Hagelin],2005-02-11,https://www.heritage.org/marriage-and-family/c...,[],"Parents, does the school your children attend ..."
301,Buyer Beware of CEDAW,[],2002-08-28,https://www.heritage.org/the-constitution/comm...,[],"In late July, when the Senate Foreign Relation..."
302,Why Any Male Student Should Think Twice Before...,[Hans A. von Spakovsky],2015-08-18,https://www.heritage.org/gender/commentary/why...,[],This should terrify any parent whose son is ab...
303,The Problems With CNN Poll Showing Opposition ...,[Elizabeth Fender],2016-06-02,https://www.heritage.org/gender/commentary/the...,[],Between North Carolina’s bathroom law and Pres...

In [3]:
## exploring our data

df.sample(10)

,title,author,date,url,takeaways,text
262,Massachusetts Can Protect Women and Kids,[Monica Burke],2018-11-06,https://www.heritage.org/gender/commentary/mas...,"[The law in question, passed in 2016, changed ...","This election cycle, there’s a question on the..."
142,New Jersey Schools Want To Talk to Kids About ...,[Jonathan Butcher],2022-04-19,https://www.heritage.org/education/commentary/...,"[This fall, New Jersey’s department of educati...",Helping your child with math homework after sc...
300,Parents Beware!,[Rebecca Hagelin],2005-02-11,https://www.heritage.org/marriage-and-family/c...,[],"Parents, does the school your children attend ..."
96,Diplomacy in Drag?,[Simon Hankinson],2023-01-12,https://www.heritage.org/gender/commentary/dip...,[Leftist political appointees now in charge at...,Who would have thought we’d need a bill “To Ba...
35,Make Miss Universe Pageant All-Female Again,[Peter Parisi],2023-11-20,https://www.heritage.org/gender/commentary/mak...,[How humiliating and disheartening must it be ...,How humiliating and disheartening must it be f...
248,Equality Act Would Create Inequality for Women,[Emilie Kao],2019-03-27,https://www.heritage.org/gender/commentary/equ...,[By embracing the ideology of “gender identity...,How ironic that House Speaker Nancy Pelosi int...
209,Bill Would Ban Gender Reassignment Procedures ...,[Andrea Jones],2020-08-24,https://www.heritage.org/gender/commentary/bil...,[The U.K.’s minister for women and equalities ...,The BBC reported back in March on a lawsuit ag...
13,A Feminine Form of Resistance,[Emma Waters],2024-08-26,https://www.heritage.org/marriage-and-family/c...,[The role of women in political fights is a ta...,The role of women in political fights is a tal...
47,Massachusetts’ Religious Bigotry Leaves Foster...,"[Thomas Jipping, Katie Blair]",2023-09-11,https://www.heritage.org/gender/commentary/mas...,[What could possibly be more important than fi...,"Religious freedom, Congress said unanimously i..."
255,7 Reasons Why the Equality Act Is Anything But,[Monica Burke],2019-03-14,https://www.heritage.org/gender/commentary/7-r...,[],Most Americans don’t want a nationwide bathroo...

In [4]:
df.columns

Index(['title', 'author', 'date', 'url', 'takeaways', 'text'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      304 non-null    object
 1   author     304 non-null    object
 2   date       279 non-null    datetime64[ns]
 3   url        304 non-null    object
 4   takeaways  304 non-null    object
 5   text       304 non-null    object
dtypes: datetime64[ns](1), object(5)
memory usage: 14.4+ KB

In [ ]:
## how to access a column

df['text']

0      On Wednesday, December 3, the U.S. Supreme Cou...
1      In two short weeks, President Donald Trump has...
2      Under the last presidential administration, pr...
3      The Supreme Court has said that parents’ right...
4      It’s difficult to envision a more dizzying exe...
                             ...
299    Between North Carolina’s bathroom law and Pres...
300    Parents, does the school your children attend ...
301    Yesterday’s post explained government’s policy...
302    A new bill in California claims to protect LGB...
303    Properly understanding sex, gender, gender ide...
Name: text, Length: 304, dtype: object

In [6]:
df['author']

0      [Hans A. von Spakovsky, Sarah Parshall Perry]
1            [Thomas  Jipping, Sarah Parshall Perry]
2                             [Sarah Parshall Perry]
3             [Paul J. Larkin, Sarah Parshall Perry]
4                             [Sarah Parshall Perry]
                           ...
299                                               []
300                               [Rebecca  Hagelin]
301                                               []
302                          [Hans A. von Spakovsky]
303                              [Elizabeth  Fender]
Name: author, Length: 304, dtype: object

In [ ]:
## cleaning:

## what do we want to do with the data?
## what kind of data do we have? Check each column's data type.
## what kind of data do we need?

In [4]:
## how to access a column?
## how to access a row from that column?

type(df['title'][0])

str

In [5]:
type(df['author'][0])

list

In [6]:
type(df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
## the type of data that we have determines what we can do with it.

# print the data type of each column by checking the first element of each column
for col in df.columns:
    print(f"{col}: {type(df[col][0])}")

title: <class 'str'>
author: <class 'list'>
date: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
url: <class 'str'>
takeaways: <class 'list'>
text: <class 'str'>

In [ ]:
## challenge: 

## we want to remove rows that have an empty value in the 'author' column.

In [11]:
## from coplit:

import numpy as np

## uses replace() function -- very useful for cleaning
df['author'].replace('', np.nan, inplace=True)
df = df.dropna(subset=['author'])

/var/folders/z6/8hbw1n6n3dq2jdw3_zjysj5sws21gh/T/ipykernel_868/2213434441.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['author'].replace('', np.nan, inplace=True)

In [13]:
# Remove rows where 'date' is NaT
df = df.dropna(subset=['date'])

In [14]:
df.sample(20)

,title,author,date,url,takeaways,text
28,Feminism: Something To Talk About,[Brenda Hafera],2024-06-14,https://www.heritage.org/civil-society/comment...,"[When many criticize feminism, they are really...",I have little patience for Simone de Beauvoir ...
14,Gender Activists to Pennsylvania Parents: We’l...,"[Thomas Jipping, Sarah Parshall Perry]",2024-10-03,https://www.heritage.org/gender/commentary/gen...,"[Nearly 1,100 school districts across the coun...",If you’re the parent of a child in a Pennsylva...
245,A Closer Read of the “Gender Wage Gap” Tells a...,[Rachel Greszler],2019-04-22,https://www.heritage.org/gender/commentary/clo...,[],Women can’t seem to get a break. They not only...
77,Judge Misreads Supreme Court in Ruling Boy’s “...,[Sarah Parshall Perry],2023-06-26,https://www.heritage.org/gender/commentary/jud...,"[Score one for the woke scolds, who now get to...","Score one for the woke scolds, who now get to ..."
269,Why the LGBT Alliance Could Be on the Brink of...,"[Spencer McCloy, Monica Burke]",2018-07-27,https://www.heritage.org/gender/commentary/why...,[A group of eight lesbians interrupted the par...,Events at the July 7 Pride in London parade re...
135,Does “Gender-Affirming Care” For Trans Kids Ac...,"[Jay P. Greene, PhD]",2022-06-15,https://www.heritage.org/gender/commentary/doe...,[Political abuse of science is emerging again ...,"When faced with divisive political arguments, ..."
89,Radical Agenda Eclipses Women at the U.N.’s Co...,[Grace Melton],2023-03-20,https://www.heritage.org/gender/commentary/rad...,"[As usual, abortion and gender ideology are co...",While the United Nations is in the midst of it...
68,Planned Parenthood Taxpayer Funding Up; Aborti...,[Melanie Israel],2023-06-13,https://www.heritage.org/life/commentary/plann...,[Taxpayer funding is at an all-time high and a...,Planned Parenthood’s 2021-2022 annual report i...
221,Compelled Speech Is Hitting Close to Home,"[Andrea Jones, Alex Richey]",2020-02-04,https://www.heritage.org/gender/commentary/com...,[“1984” is becoming more and more prescient by...,George Orwell wrote his dystopian novel “1984”...
155,Democrats Erase Women Through Budget “Reconcil...,"[Jay W. Richards, PhD, Jared Eckert]",2021-10-15,https://www.heritage.org/gender/commentary/dem...,[The trajectory is unmistakable: Whenever feas...,"According to Senate rules, a reconciliation pa..."
140,Lia Thomas Was Just the Beginning. Biden Admin...,"[Sarah Parshall Perry, Abby Kassal]",2022-04-11,https://www.heritage.org/gender/commentary/lia...,[Women are the clear losers—finding themselves...,This year marks the 50th anniversary of the pa...
183,Young Children Are Being Targeted With Sexual ...,"[Jared Eckert, Makenna McCoy]",2021-06-11,https://www.heritage.org/marriage-and-family/c...,"[As this year’s LGBT+ Pride Month has shown, y...","Dating back to the 1860s, Americans celebrate ..."
291,Just Because Liberals Call Something ‘Discrimi...,"[Ryan T. Anderson, Ph.D.]",2017-03-02,https://www.heritage.org/gender/commentary/jus...,[Liberals are calling anything they dislike “d...,The biggest problem with current sexual orient...
101,"If You Want Our Help, You Must Accept Our Gend...",[Grace Melton],2023-02-16,https://www.heritage.org/gender/commentary/if-...,[President Biden is directing the full financi...,The U.S. government is sparing no effort to sp...
19,School Gender Policies Harm Students and Viola...,[Thomas Jipping],2024-04-16,https://www.heritage.org/education/commentary/...,[The centerpiece of these policies is a studen...,"Like others around the country, the Rockford, ..."
231,Males Don’t Belong in Women’s Sports—Even If T...,"[Andrea Jones, Clare Hepler]",2019-11-27,https://www.heritage.org/gender/commentary/mal...,[Fair competition in women’s sports remains un...,Fair competition in women’s sports remains und...
58,Former Teammate of Lia Thomas Speaks Out,"[Kevin D. Roberts, PhD]",2023-08-16,https://www.heritage.org/gender/commentary/for...,[],"In 2019, the University of Pennsylvania's swim..."
214,DoD’s Transgender Entrance Policy Exists for a...,[Thomas Spoehr],2020-07-14,https://www.heritage.org/gender/commentary/dod...,"[In deployed situations, a constant flow of me...",Service in the U.S. armed forces is a privileg...
280,A New York Times Writer’s Reckless Hit Piece o...,"[Ryan T. Anderson, Ph.D.]",2018-02-28,https://www.heritage.org/gender/commentary/new...,[We lose the ability to effectively call out b...,"Anti-trans bigotry exists. It’s wrong, and we ..."
254,Google’s Internal Audit Bucks the Narrative on...,[Rachel Greszler],2019-03-05,https://www.heritage.org/jobs-and-labor/commen...,[],Whether it’s the result of political pressure ...

In [19]:
# write df to new json file
df.to_json('cleaned.json', orient='records', lines=True)

In [15]:
# pull out "text" column
text = df['text']

In [18]:
#write text to a file called "text.txt"
with open('text.txt', 'w') as f:
    for line in text:
        f.write(line + '\n\n')